SET NAMES UTF8;
DROP DATABASE IF EXISTS user;
CREATE DATABASE user CHARSET=utf8;
USE user;
CREATE TABLE reg(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    unum VARCHAR(11),
    upwd VARCHAR(32),
    ltime BIGINT
);
INSERT INTO reg VALUES(null,18824309984,123456,now());